language: python
python:
  - 2.7

services:
  - docker

install:
  # Install mocha for testing express app
  - npm install -g mocha
  - npm install supertest
  - npm install

before_script:
  # Build docker image
  - docker build -t adyen-card-tester .
  - docker run -d -p 127.0.0.1:80:5000 -e ADYEN_KEY="adyen public key" --name adyen-card-tester adyen-card-tester
  - wget --quiet 127.0.0.1:80

script:
  - wget --quiet 127.0.0.1:80
  - docker ps | grep -q adyen-card-tester
  - mocha

after_failure:
  - docker logs adyen-card-tester
